### ISSUE TITLE
five_percent.py 'local variable df referenced before assignment'

### ISSUE THREAD

**Issue by miali88** [PythonForForex/ib_insync-guide-interactive-brokers#1]
I've copied the script as is, however I'm getting the error:

`line 11, in new_data
    df.loc[ticker.time] = ticker.last
UnboundLocalError: local variable 'df' referenced before assignment`

**Comment by PythonForForex** [comment]
The Dataframe needed to be initialized ahead of the functions. I've made the change and pushed the latest code. If you still have an issue do let me know.

**Comment by miali88** [comment]
Thanks for the response. Unfortunately the same error persists. I had tried this too, are you getting the same response?

**Comment by PythonForForex** [comment]
Changed the df to a global variable within the function - tested it and it is working now. Another option would have been to save the df within a dictionary as we've done in other tutorials.

Let me know if you have any issues.

**Comment by miali88** [comment]
Works like a charm. Ty!
